export const setupPage = `<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Sakura-MCP-Server 安装向导</title>
  <style>
    :root{color-scheme:dark;--bg:#0c1017;--card:#151b26;--line:#293244;--text:#edf2fa;--muted:#99a6ba;--accent:#e58aa3;--ok:#67d6a3;--bad:#ff7b86}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#252039 0,transparent 35%),var(--bg);font:15px/1.6 system-ui,sans-serif;color:var(--text)}main{max-width:920px;margin:auto;padding:48px 20px 80px}header{margin-bottom:28px}h1{font-size:34px;margin:0 0 8px}.brand{color:var(--accent)}.sub{color:var(--muted)}.steps{display:flex;gap:8px;margin:24px 0}.step{height:5px;flex:1;background:var(--line);border-radius:8px}.step.active{background:var(--accent)}section{display:none;background:rgba(21,27,38,.94);border:1px solid var(--line);border-radius:18px;padding:26px;box-shadow:0 16px 50px #0005}section.active{display:block}h2{margin-top:0}h3{margin:24px 0 10px}label{display:block;margin:13px 0 5px;color:#cbd5e5}input,select{width:100%;padding:11px 12px;border:1px solid var(--line);border-radius:9px;background:#0e141e;color:var(--text)}input:focus{outline:2px solid #e58aa355;border-color:var(--accent)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.actions{display:flex;justify-content:space-between;gap:12px;margin-top:26px}button{border:0;border-radius:9px;padding:11px 18px;font-weight:650;cursor:pointer;background:var(--accent);color:#22141a}button.secondary{background:#293244;color:var(--text)}button:disabled{opacity:.45;cursor:not-allowed}.result{white-space:pre-wrap;background:#0e141e;border:1px solid var(--line);border-radius:9px;padding:12px;margin-top:14px;color:var(--muted);min-height:48px}.ok{color:var(--ok)}.bad{color:var(--bad)}.notice{padding:12px 14px;border-left:3px solid var(--accent);background:#251d29;border-radius:5px}.check{display:flex;gap:9px;align-items:center;margin:14px 0}.check input{width:auto}.hidden{display:none}@media(max-width:650px){.grid{grid-template-columns:1fr}main{padding-top:28px}section{padding:20px}}
  </style>
</head>
<body><main>
  <header><h1><span class="brand">Sakura</span>-MCP-Server</h1><div class="sub">多用户 AI 长期记忆平台 · 首次安装向导</div></header>
  <div class="steps" id="steps"></div>
  <section data-step="0" class="active"><h2>欢迎</h2><p>向导会检查数据库、配置 Authentik，并可连接 OpenAI-compatible 或 Ollama。数据库地址、安装令牌和配置加密密钥必须预先写入服务器 <code>.env</code>。</p><div class="notice">安装完成后向导将锁定。模型 API Key 使用 AES-256-GCM 加密后存入数据库，不会返回浏览器。</div><label>安装令牌（SETUP_TOKEN）</label><input id="setupToken" type="password" autocomplete="off" placeholder="服务器 .env 中的 SETUP_TOKEN"><div class="actions"><span></span><button onclick="diagnose()">检查环境</button></div><div id="diag" class="result">等待检查……</div></section>
  <section data-step="1"><h2>Authentik 身份认证</h2><div class="grid"><div><label>Issuer</label><input id="issuer" placeholder="https://login.example.com/application/o/sakura-mcp/"></div><div><label>Audience</label><input id="audience" placeholder="https://mcp.example.com"></div></div><label>Client ID（Public + PKCE）</label><input id="clientId" placeholder="Authentik OAuth Client ID"><label>JWKS URI</label><input id="jwksUri" placeholder="https://login.example.com/application/o/sakura-mcp/jwks/"><div class="grid"><div><label>Authorization URL</label><input id="authorizationUrl" placeholder="https://login.example.com/application/o/authorize/"></div><div><label>Token URL</label><input id="tokenUrl" placeholder="https://login.example.com/application/o/token/"></div></div><label>UserInfo URL（可选）</label><input id="userinfoUrl" placeholder="https://login.example.com/application/o/userinfo/"><label>Scope Claim</label><input id="scopeClaim" value="scope"><label>首位系统管理员邮箱</label><input id="adminEmail" type="email" placeholder="admin@example.com"><div class="actions"><button class="secondary" onclick="go(0)">上一步</button><button onclick="testAuthentik()">测试并继续</button></div><div id="authResult" class="result">尚未测试。</div></section>
  <section data-step="2"><h2>AI 模型服务</h2><label>Provider</label><select id="provider" onchange="providerChanged()"><option value="none">暂不配置</option><option value="openai">OpenAI-compatible</option><option value="ollama">Ollama</option></select><div id="providerFields" class="hidden"><label>Base URL</label><input id="providerBase"><div id="apiKeyRow"><label>API Key</label><input id="providerKey" type="password" autocomplete="off"></div><div class="grid"><div><label>Chat Model</label><input id="chatModel"></div><div><label>Embedding Model</label><input id="embeddingModel"></div></div></div><div class="actions"><button class="secondary" onclick="go(1)">上一步</button><button onclick="testProviderAndContinue()">测试并继续</button></div><div id="providerResult" class="result">可跳过，之后在管理后台配置。</div></section>
  <section data-step="3"><h2>确认安装</h2><p>将写入 Authentik、管理员白名单及可选模型配置，并永久锁定安装入口。</p><div id="summary" class="result"></div><label class="check"><input id="confirm" type="checkbox">我已保存服务器的 CONFIG_ENCRYPTION_KEY，并确认开始安装</label><div class="actions"><button class="secondary" onclick="go(2)">上一步</button><button id="installButton" onclick="completeSetup()">完成安装</button></div><div id="completeResult" class="result">等待确认。</div></section>
  <section data-step="4"><h2 class="ok">安装完成</h2><p>Sakura-MCP-Server 已锁定安装向导。现在可以通过 Authentik 登录管理后台，并将 Agent 连接到 MCP URL。</p><div class="result" id="finalUrls"></div></section>
</main><script>
let current=0;const total=5;const $=id=>document.getElementById(id);const token=()=>$('setupToken').value;
function renderSteps(){ $('steps').innerHTML=Array.from({length:total},(_,i)=>'<div class="step '+(i<=current?'active':'')+'"></div>').join('');document.querySelectorAll('section').forEach(s=>s.classList.toggle('active',Number(s.dataset.step)===current)); }
function go(n){current=n;renderSteps();if(n===3)buildSummary()}
async function api(path,body){const r=await fetch('/api/setup/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json','X-Setup-Token':token()},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({error:'响应不是 JSON'}));if(!r.ok)throw new Error(data.error_description||data.error||'请求失败 '+r.status);return data}
function authData(){return{issuer:$('issuer').value,audience:$('audience').value,jwksUri:$('jwksUri').value,scopeClaim:$('scopeClaim').value,clientId:$('clientId').value,authorizationUrl:$('authorizationUrl').value,tokenUrl:$('tokenUrl').value,userinfoUrl:$('userinfoUrl').value||undefined}}
function providerData(){const p=$('provider').value;if(p==='none')return{};const data={baseUrl:$('providerBase').value,chatModel:$('chatModel').value||undefined,embeddingModel:$('embeddingModel').value||undefined};return p==='openai'?{openaiCompatible:{...data,apiKey:$('providerKey').value||undefined}}:{ollama:data}}
async function diagnose(){try{const d=await api('diagnostics');$('diag').className='result ok';$('diag').textContent='✓ PostgreSQL 正常\n✓ pgvector '+(d.pgvectorVersion||'未安装')+'\n✓ 已应用迁移：'+d.migrations.map(x=>x.name).join(', ');if(!d.pgvectorVersion)throw new Error('pgvector 扩展未安装');go(1)}catch(e){$('diag').className='result bad';$('diag').textContent='✗ '+e.message}}
async function testAuthentik(){try{const d=await api('test-authentik',{authentik:authData()});$('authResult').className='result ok';$('authResult').textContent='✓ Authentik 连接成功\n签名密钥：'+d.signingKeys;go(2)}catch(e){$('authResult').className='result bad';$('authResult').textContent='✗ '+e.message}}
function providerChanged(){const p=$('provider').value;$('providerFields').classList.toggle('hidden',p==='none');$('apiKeyRow').classList.toggle('hidden',p!=='openai');$('providerBase').value=p==='ollama'?'http://host.docker.internal:11434':p==='openai'?'https://api.openai.com/v1':''}
async function testProviderAndContinue(){if($('provider').value==='none'){go(3);return}try{const d=await api('test-provider',providerData());$('providerResult').className='result ok';$('providerResult').textContent='✓ '+d.provider+' 连接成功';go(3)}catch(e){$('providerResult').className='result bad';$('providerResult').textContent='✗ '+e.message}}
function buildSummary(){$('summary').textContent='管理员：'+$('adminEmail').value+'\nAuthentik：'+$('issuer').value+'\nAudience：'+$('audience').value+'\nAI Provider：'+$('provider').value}
async function completeSetup(){if(!$('confirm').checked){$('completeResult').className='result bad';$('completeResult').textContent='请先确认配置加密密钥已安全保存。';return}const b=$('installButton');b.disabled=true;try{await api('complete',{administratorEmail:$('adminEmail').value,authentik:authData(),...providerData()});$('completeResult').className='result ok';$('completeResult').textContent='✓ 安装成功';$('finalUrls').textContent='MCP URL：'+location.origin+'/mcp\n健康检查：'+location.origin+'/health';go(4)}catch(e){b.disabled=false;$('completeResult').className='result bad';$('completeResult').textContent='✗ '+e.message}}
fetch('/api/setup/status').then(r=>r.json()).then(s=>{if(s.completed){current=4;$('finalUrls').textContent='系统已经完成安装。\nMCP URL：'+location.origin+'/mcp'}renderSteps()}).catch(()=>renderSteps());
</script></body></html>`;